apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-gitrepo
  labels:
    app: nginx-pod-gitrepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-gitrepo
  template:
    metadata:
      labels:
        app: nginx-pod-gitrepo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-gitrepo
spec:
  selector:
    app: nginx-pod-gitrepo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP